project:
  type: website  
  output-dir: docs

website:
  title: "AboutMe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: CV/CV_Zoe.qmd
        text: Curriculum Vitae

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true


knitr:
  opts_chunk: 
    echo: false
    warning: false

